package com.ardit.banking;

import static org.assertj.core.api.Assertions.assertThat;

import javax.sql.DataSource;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.core.io.ClassPathResource;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.jdbc.datasource.init.ResourceDatabasePopulator;

class MigrationV13SeedAdminDashboardCashFlowTests {

    private JdbcTemplate jdbcTemplate;

    @BeforeEach
    void setUp() {
        DataSource dataSource = new DriverManagerDataSource(
            "jdbc:h2:mem:v13-seed;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE",
            "sa",
            ""
        );
        jdbcTemplate = new JdbcTemplate(dataSource);

        jdbcTemplate.execute("DROP ALL OBJECTS");
        jdbcTemplate.execute("""
            CREATE TABLE users (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username VARCHAR(50) NOT NULL UNIQUE
            )
            """);
        jdbcTemplate.execute("""
            CREATE TABLE accounts (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                owner_user_id BIGINT NOT NULL,
                account_number VARCHAR(34) NOT NULL UNIQUE,
                iban VARCHAR(34),
                base_number VARCHAR(6),
                account_class_code VARCHAR(3),
                serial_number INTEGER,
                account_type VARCHAR(30) NOT NULL,
                currency_code VARCHAR(3) NOT NULL,
                name VARCHAR(120) NOT NULL,
                status VARCHAR(20) NOT NULL,
                current_balance NUMERIC(19, 2) NOT NULL,
                available_balance NUMERIC(19, 2) NOT NULL,
                overdraft_limit NUMERIC(19, 2) NOT NULL,
                annual_interest_rate NUMERIC(7, 4),
                opened_at TIMESTAMP NOT NULL
            )
            """);
        jdbcTemplate.execute("""
            CREATE TABLE transactions (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                account_id BIGINT NOT NULL,
                transaction_reference VARCHAR(64) NOT NULL UNIQUE,
                external_reference VARCHAR(64),
                transaction_type VARCHAR(30) NOT NULL,
                transaction_status VARCHAR(20) NOT NULL,
                direction VARCHAR(10) NOT NULL,
                currency_code VARCHAR(3) NOT NULL,
                amount NUMERIC(19, 2) NOT NULL,
                description VARCHAR(280) NOT NULL,
                counterparty_name VARCHAR(140),
                counterparty_account VARCHAR(34),
                booking_timestamp TIMESTAMP NOT NULL,
                value_date DATE NOT NULL,
                balance_after NUMERIC(19, 2) NOT NULL,
                fx_rate NUMERIC(19, 8),
                fx_reference_amount NUMERIC(19, 2),
                fx_reference_currency VARCHAR(3)
            )
            """);
        jdbcTemplate.update("INSERT INTO users (username) VALUES (?)", "admin");
    }

    @Test
    void seedsAdminAccountAndMonthlyCashFlowTransactions() {
        ResourceDatabasePopulator populator = new ResourceDatabasePopulator(
            new ClassPathResource("db/migration/V13__seed_admin_dashboard_cash_flow.sql"),
            new ClassPathResource("db/migration/V14__normalize_admin_dashboard_cash_flow.sql"),
            new ClassPathResource("db/migration/V15__restore_admin_dashboard_cash_flow_transactions.sql")
        );
        populator.execute(jdbcTemplate.getDataSource());

        Integer accountCount = jdbcTemplate.queryForObject(
            "SELECT COUNT(*) FROM accounts WHERE account_number = '2121100912000101'",
            Integer.class
        );
        Integer transactionCount = jdbcTemplate.queryForObject(
            "SELECT COUNT(*) FROM transactions WHERE transaction_reference LIKE 'ADM-CHART-%'",
            Integer.class
        );
        String accountName = jdbcTemplate.queryForObject(
            "SELECT name FROM accounts WHERE account_number = '2121100912000101'",
            String.class
        );
        String currentBalance = jdbcTemplate.queryForObject(
            "SELECT CAST(current_balance AS VARCHAR) FROM accounts WHERE account_number = '2121100912000101'",
            String.class
        );
        String februaryCreditType = jdbcTemplate.queryForObject(
            "SELECT transaction_type FROM transactions WHERE transaction_reference = 'ADM-CHART-05'",
            String.class
        );
        String mayIncomeAmount = jdbcTemplate.queryForObject(
            "SELECT CAST(amount AS VARCHAR) FROM transactions WHERE transaction_reference = 'ADM-CHART-11'",
            String.class
        );
        String mayFeeBalanceAfter = jdbcTemplate.queryForObject(
            "SELECT CAST(balance_after AS VARCHAR) FROM transactions WHERE transaction_reference = 'ADM-CHART-14'",
            String.class
        );

        assertThat(accountCount).isEqualTo(1);
        assertThat(transactionCount).isEqualTo(14);
        assertThat(accountName).isEqualTo("Admin Operating Account");
        assertThat(currentBalance).isEqualTo("17540.00");
        assertThat(februaryCreditType).isEqualTo("ADJUSTMENT");
        assertThat(mayIncomeAmount).isEqualTo("4100.00");
        assertThat(mayFeeBalanceAfter).isEqualTo("17540.00");
    }

    @Test
    void restoresAdminCashFlowTransactionsAfterManualDeletion() {
        ResourceDatabasePopulator initialPopulator = new ResourceDatabasePopulator(
            new ClassPathResource("db/migration/V13__seed_admin_dashboard_cash_flow.sql"),
            new ClassPathResource("db/migration/V14__normalize_admin_dashboard_cash_flow.sql")
        );
        initialPopulator.execute(jdbcTemplate.getDataSource());

        jdbcTemplate.update("DELETE FROM transactions WHERE transaction_reference LIKE 'ADM-CHART-%'");

        ResourceDatabasePopulator restorePopulator = new ResourceDatabasePopulator(
            new ClassPathResource("db/migration/V15__restore_admin_dashboard_cash_flow_transactions.sql")
        );
        restorePopulator.execute(jdbcTemplate.getDataSource());

        Integer restoredTransactionCount = jdbcTemplate.queryForObject(
            "SELECT COUNT(*) FROM transactions WHERE transaction_reference LIKE 'ADM-CHART-%'",
            Integer.class
        );
        String restoredMayIncomeAmount = jdbcTemplate.queryForObject(
            "SELECT CAST(amount AS VARCHAR) FROM transactions WHERE transaction_reference = 'ADM-CHART-11'",
            String.class
        );
        String restoredEndingBalance = jdbcTemplate.queryForObject(
            "SELECT CAST(balance_after AS VARCHAR) FROM transactions WHERE transaction_reference = 'ADM-CHART-14'",
            String.class
        );

        assertThat(restoredTransactionCount).isEqualTo(14);
        assertThat(restoredMayIncomeAmount).isEqualTo("4100.00");
        assertThat(restoredEndingBalance).isEqualTo("17540.00");
    }
}
