import { ChangeDetectionStrategy, Component, input, output } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';

import type { AccountCurrency, AccountType, CreateAccountRequest } from '../../core/services/account-api.service';
import { HlmButton } from '../../shared/ui/spartan/button';
import {
  HlmDialog,
  HlmDialogClose,
  HlmDialogContent,
  HlmDialogDescription,
  HlmDialogFooter,
  HlmDialogHeader,
  HlmDialogPortal,
  HlmDialogTitle
} from '@spartan/dialog';
import { HlmInput } from '../../shared/ui/spartan/input';
import { HlmLabel } from '../../shared/ui/spartan/label';

type AccountFormOption<T extends string> = {
  readonly value: T;
  readonly label: string;
  readonly meta: string;
};

@Component({
  selector: 'app-create-account-dialog',
  imports: [
    ReactiveFormsModule,
    HlmButton,
    HlmDialog,
    HlmDialogClose,
    HlmDialogContent,
    HlmDialogDescription,
    HlmDialogFooter,
    HlmDialogHeader,
    HlmDialogPortal,
    HlmDialogTitle,
    HlmInput,
    HlmLabel
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <hlm-dialog [state]="open() ? 'open' : 'closed'" (stateChanged)="handleStateChanged($event)">
      <hlm-dialog-content
        *hlmDialogPortal="let ctx"
        class="flex max-h-[min(88vh,42rem)] w-[calc(100vw-2rem)] max-w-2xl flex-col overflow-hidden rounded-lg border-border/70 bg-card/96 p-0 backdrop-blur-xl"
      >
        <div class="flex min-h-0 flex-col">
          <div hlmDialogHeader class="gap-3 border-b border-border/70 px-6 py-6 sm:px-8">
            <h2 hlmDialogTitle class="font-display text-4xl tracking-tight text-card-foreground">Create a new account</h2>
            <p hlmDialogDescription class="max-w-xl text-sm leading-6 text-muted-foreground">
              Description, product type, and currency are entered here. Base number, class code, serial number, account number, and IBAN are generated by the backend.
            </p>
          </div>

          <form [formGroup]="form" (ngSubmit)="submit()" class="flex min-h-0 flex-1 flex-col">
            <div class="flex min-h-0 flex-1 flex-col gap-6 overflow-y-auto px-6 py-6 sm:px-8">
              <div class="flex flex-col gap-2">
                <label hlmLabel for="account-name" class="text-sm font-semibold tracking-[0.18em] text-muted-foreground uppercase">Description</label>
                <input
                  id="account-name"
                  hlmInput
                  type="text"
                  formControlName="name"
                  class="rounded-lg border border-border/80 bg-background/70 px-4 py-3 text-base text-foreground shadow-sm transition focus-visible:ring-4 focus-visible:ring-ring/20"
                  placeholder="e.g. Daily operating account…"
                />
              </div>

              <div class="grid gap-5 md:grid-cols-2">
                <div class="flex flex-col gap-2">
                  <label hlmLabel for="account-type" class="text-sm font-semibold tracking-[0.18em] text-muted-foreground uppercase">Type</label>
                  <select
                    id="account-type"
                    formControlName="type"
                    class="w-full rounded-lg border border-border/80 bg-background/70 bg-[linear-gradient(45deg,transparent_50%,color-mix(in_oklab,var(--muted-foreground)_82%,transparent)_50%),linear-gradient(135deg,color-mix(in_oklab,var(--muted-foreground)_82%,transparent)_50%,transparent_50%)] bg-[position:calc(100%-1.35rem)_calc(50%-0.15rem),calc(100%-0.95rem)_calc(50%-0.15rem)] bg-[size:0.45rem_0.45rem,0.45rem_0.45rem] bg-no-repeat px-4 py-3 text-base text-foreground shadow-sm outline-none transition focus-visible:ring-4 focus-visible:ring-ring/20"
                  >
                    @for (option of typeOptions(); track option.value) {
                      <option [value]="option.value">{{ option.label }} - {{ option.meta }}</option>
                    }
                  </select>
                </div>

                <div class="flex flex-col gap-2">
                  <label hlmLabel for="account-currency" class="text-sm font-semibold tracking-[0.18em] text-muted-foreground uppercase">Currency</label>
                  <select
                    id="account-currency"
                    formControlName="currency"
                    class="w-full rounded-lg border border-border/80 bg-background/70 bg-[linear-gradient(45deg,transparent_50%,color-mix(in_oklab,var(--muted-foreground)_82%,transparent)_50%),linear-gradient(135deg,color-mix(in_oklab,var(--muted-foreground)_82%,transparent)_50%,transparent_50%)] bg-[position:calc(100%-1.35rem)_calc(50%-0.15rem),calc(100%-0.95rem)_calc(50%-0.15rem)] bg-[size:0.45rem_0.45rem,0.45rem_0.45rem] bg-no-repeat px-4 py-3 text-base text-foreground shadow-sm outline-none transition focus-visible:ring-4 focus-visible:ring-ring/20"
                  >
                    @for (option of currencyOptions(); track option.value) {
                      <option [value]="option.value">{{ option.label }} - {{ option.meta }}</option>
                    }
                  </select>
                </div>
              </div>

              <div class="flex flex-col gap-2">
                <label hlmLabel for="initial-deposit" class="text-sm font-semibold tracking-[0.18em] text-muted-foreground uppercase">Initial deposit</label>
                <input
                  id="initial-deposit"
                  hlmInput
                  type="number"
                  min="0"
                  step="0.01"
                  formControlName="initialDeposit"
                  class="rounded-lg border border-border/80 bg-background/70 px-4 py-3 text-base text-foreground shadow-sm transition focus-visible:ring-4 focus-visible:ring-ring/20"
                />
              </div>
            </div>

            <div class="border-t border-border/70 px-6 py-5 sm:px-8">
              @if (submitErrorMessage()) {
                <p class="mb-4 rounded-lg border border-red-500/20 bg-red-500/8 px-4 py-3 text-sm font-medium text-red-700 dark:text-red-300">
                  {{ submitErrorMessage() }}
                </p>
              }

              <div hlmDialogFooter class="justify-end gap-3">
                <button
                  hlmBtn
                  type="button"
                  variant="outline"
                  class="rounded-lg"
                  hlmDialogClose
                >
                  Cancel
                </button>
                <button
                  hlmBtn
                  type="submit"
                  class="rounded-lg"
                  [disabled]="submitting()"
                >
                  {{ submitting() ? 'Creating…' : 'Create account' }}
                </button>
              </div>
            </div>
          </form>
        </div>
      </hlm-dialog-content>
    </hlm-dialog>
  `
})
export class CreateAccountDialogComponent {
  private readonly fb = new FormBuilder();

  readonly open = input.required<boolean>();
  readonly submitting = input(false);
  readonly submitErrorMessage = input<string | null>(null);
  readonly typeOptions = input.required<readonly AccountFormOption<AccountType>[]>();
  readonly currencyOptions = input.required<readonly AccountFormOption<AccountCurrency>[]>();

  readonly openChange = output<boolean>();
  readonly createAccount = output<CreateAccountRequest>();

  protected readonly form = this.fb.nonNullable.group({
    name: ['', [Validators.required, Validators.maxLength(120)]],
    type: ['CURRENT' as AccountType, [Validators.required]],
    currency: ['EUR' as AccountCurrency, [Validators.required]],
    initialDeposit: [0, [Validators.required, Validators.min(0)]]
  });

  protected handleStateChanged(state: string): void {
    const isOpen = state === 'open';
    this.openChange.emit(isOpen);
    if (!isOpen) {
      this.form.reset({
        name: '',
        type: 'CURRENT',
        currency: 'EUR',
        initialDeposit: 0
      });
    }
  }

  protected submit(): void {
    if (this.form.invalid || this.submitting()) {
      this.form.markAllAsTouched();
      return;
    }

    const rawValue = this.form.getRawValue();
    this.createAccount.emit({
      name: rawValue.name.trim(),
      type: rawValue.type,
      currency: rawValue.currency,
      initialDeposit: Number(rawValue.initialDeposit)
    });
  }
}
