CREATE TABLE transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    account_id BIGINT NOT NULL,
    transaction_reference VARCHAR(64) NOT NULL,
    external_reference VARCHAR(64),
    transaction_type VARCHAR(30) NOT NULL,
    transaction_status VARCHAR(20) NOT NULL,
    direction VARCHAR(10) NOT NULL,
    currency_code VARCHAR(3) NOT NULL,
    amount NUMERIC(19, 2) NOT NULL,
    description VARCHAR(280) NOT NULL,
    counterparty_name VARCHAR(140),
    counterparty_account VARCHAR(34),
    booking_timestamp TIMESTAMP NOT NULL,
    value_date DATE NOT NULL,
    balance_after NUMERIC(19, 2) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT transactions_pkey PRIMARY KEY (id),
    CONSTRAINT fk_transactions_account FOREIGN KEY (account_id) REFERENCES accounts(id),
    CONSTRAINT uq_transactions_reference UNIQUE (transaction_reference),
    CONSTRAINT chk_transactions_reference_nonblank CHECK (length(trim(transaction_reference)) > 0),
    CONSTRAINT chk_transactions_description_nonblank CHECK (length(trim(description)) > 0),
    CONSTRAINT chk_transactions_type CHECK (
        transaction_type IN ('DEPOSIT', 'WITHDRAWAL', 'TRANSFER_IN', 'TRANSFER_OUT', 'PAYMENT', 'FEE', 'INTEREST', 'ADJUSTMENT')
    ),
    CONSTRAINT chk_transactions_status CHECK (
        transaction_status IN ('PENDING', 'BOOKED', 'FAILED', 'REVERSED')
    ),
    CONSTRAINT chk_transactions_direction CHECK (
        direction IN ('DEBIT', 'CREDIT')
    ),
    CONSTRAINT chk_transactions_currency CHECK (
        currency_code IN ('EUR', 'USD', 'GBP', 'ALL')
    ),
    CONSTRAINT chk_transactions_amount_positive CHECK (amount > 0)
);

CREATE INDEX idx_transactions_account_booking_timestamp ON transactions (account_id, booking_timestamp DESC);
CREATE INDEX idx_transactions_account_value_date ON transactions (account_id, value_date DESC);
