CREATE TABLE exchange_rates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    base_currency VARCHAR(3) NOT NULL,
    quote_currency VARCHAR(3) NOT NULL,
    rate NUMERIC(19, 8) NOT NULL,
    source VARCHAR(80) NOT NULL,
    valid_from TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT exchange_rates_pkey PRIMARY KEY (id),
    CONSTRAINT chk_exchange_rates_currency_pair CHECK (base_currency <> quote_currency),
    CONSTRAINT chk_exchange_rates_base_currency CHECK (base_currency IN ('EUR', 'USD', 'GBP', 'ALL')),
    CONSTRAINT chk_exchange_rates_quote_currency CHECK (quote_currency IN ('EUR', 'USD', 'GBP', 'ALL')),
    CONSTRAINT chk_exchange_rates_rate_positive CHECK (rate > 0),
    CONSTRAINT chk_exchange_rates_source_nonblank CHECK (length(trim(source)) > 0)
);

CREATE INDEX idx_exchange_rates_pair_valid_from
    ON exchange_rates (base_currency, quote_currency, valid_from DESC);

ALTER TABLE transactions
    ADD COLUMN IF NOT EXISTS fx_rate NUMERIC(19, 8),
    ADD COLUMN IF NOT EXISTS fx_reference_amount NUMERIC(19, 2),
    ADD COLUMN IF NOT EXISTS fx_reference_currency VARCHAR(3),
    ADD CONSTRAINT chk_transactions_fx_reference_currency
        CHECK (fx_reference_currency IS NULL OR fx_reference_currency IN ('EUR', 'USD', 'GBP', 'ALL')),
    ADD CONSTRAINT chk_transactions_fx_reference_amount
        CHECK (fx_reference_amount IS NULL OR fx_reference_amount > 0),
    ADD CONSTRAINT chk_transactions_fx_rate
        CHECK (fx_rate IS NULL OR fx_rate > 0);
