CREATE TABLE accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    owner_user_id BIGINT NOT NULL,
    account_number VARCHAR(34) NOT NULL,
    iban VARCHAR(34),
    account_type VARCHAR(30) NOT NULL,
    currency_code VARCHAR(3) NOT NULL,
    name VARCHAR(120) NOT NULL,
    status VARCHAR(20) NOT NULL,
    current_balance NUMERIC(19, 2) NOT NULL,
    available_balance NUMERIC(19, 2) NOT NULL,
    overdraft_limit NUMERIC(19, 2) NOT NULL DEFAULT 0.00,
    annual_interest_rate NUMERIC(7, 4),
    opened_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    closed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT accounts_pkey PRIMARY KEY (id),
    CONSTRAINT fk_accounts_owner_user FOREIGN KEY (owner_user_id) REFERENCES users(id),
    CONSTRAINT uq_accounts_account_number UNIQUE (account_number),
    CONSTRAINT uq_accounts_iban UNIQUE (iban),
    CONSTRAINT chk_accounts_account_number_nonblank CHECK (length(trim(account_number)) > 0),
    CONSTRAINT chk_accounts_name_nonblank CHECK (length(trim(name)) > 0),
    CONSTRAINT chk_accounts_type CHECK (account_type IN ('CURRENT', 'SAVINGS', 'SAVINGS_PLAN')),
    CONSTRAINT chk_accounts_currency CHECK (currency_code IN ('EUR', 'USD', 'GBP', 'ALL')),
    CONSTRAINT chk_accounts_status CHECK (status IN ('ACTIVE', 'BLOCKED', 'DORMANT', 'CLOSED')),
    CONSTRAINT chk_accounts_overdraft_limit_nonnegative CHECK (overdraft_limit >= 0),
    CONSTRAINT chk_accounts_closed_at_consistency CHECK (
        (status = 'CLOSED' AND closed_at IS NOT NULL) OR (status <> 'CLOSED' AND closed_at IS NULL)
    ),
    CONSTRAINT chk_accounts_interest_rate_range CHECK (
        annual_interest_rate IS NULL OR (annual_interest_rate >= 0 AND annual_interest_rate <= 100)
    )
);

CREATE INDEX idx_accounts_owner_user_id ON accounts (owner_user_id);
CREATE INDEX idx_accounts_status ON accounts (status);
CREATE INDEX idx_accounts_currency_code ON accounts (currency_code);
