spring:
  application:
    name: banking-api
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/banking}
    username: ${DB_USERNAME:banking}
    password: ${DB_PASSWORD:banking}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    locations: classpath:db/migration

security:
  jwt:
    secret: ${JWT_SECRET:change-this-secret-key-change-this-secret-key}
    expiration-minutes: ${JWT_EXPIRATION_MINUTES:60}
    refresh-expiration-days: ${JWT_REFRESH_EXPIRATION_DAYS:14}

banking:
  account:
    numbering:
      country-code: ${BANKING_ACCOUNT_COUNTRY_CODE:AL}
      bank-code: ${BANKING_ACCOUNT_BANK_CODE:21211009}
      local-account-number-length: ${BANKING_ACCOUNT_LOCAL_NUMBER_LENGTH:11}
      iban-account-number-length: ${BANKING_ACCOUNT_IBAN_NUMBER_LENGTH:16}
      base-number-length: ${BANKING_ACCOUNT_BASE_NUMBER_LENGTH:6}
      serial-length: ${BANKING_ACCOUNT_SERIAL_LENGTH:2}

